name: Conventional Commits

on:
  # https://github.com/marketplace/actions/semantic-pull-request#event-triggers
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  merge_group:

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-slim
    steps:
      - name: "Checkout"
        if: ${{ github.event_name == 'pull_request' }}
        uses: "actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8" # v6
        with:
          show-progress: false

      - name: "Check commit"
        if: ${{ github.event_name == 'pull_request' }}
        uses: benhodgson87/conventional-pull-request-action@14ff798e4d745c3e3e951f6ef472ff598b9c47a5 # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitlintRulesPath: ".github/commitlint.config.js"
